# PARAMETERS FOR RHODON ROBOT
$(var namespace):
  #-------------------------------------------------
  # HW DRIVERS
  #-------------------------------------------------
  
  hokuyo:
    ros__parameters:
      angle_max: 1.4
      angle_min: -1.4
      ip_port: 1853723
      #serial_port: '/dev/sensors/hokuyo_urg'
      serial_port: '/dev/ttyACM0'
      serial_baud: 115200
      laser_frame_id: 'laser_link'
      laser_topic_name: 'scan'
      calibrate_time: False
      default_user_latency: -0.2
      diagnostics_tolerance: 0.05
      diagnostics_window_time: 5.0
      error_limit: 4
      get_detailed_status: False
      publish_intensity: False
      publish_multiecho: False
      cluster: 1
      skip: 0

  
